### ISSUE TITLE
Trying to establish connection with NetProfiler('$hostname',auth=UserAuth('$user','$password'))

### ISSUE THREAD

**Issue by ericgcoker** [riverbed/steelscript-netprofiler#2]
I am trying to authenticate via 
`p = NetProfiler('$hostname', auth=UserAuth('$username', '$password'))`

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='50.320.71.85', port=443): Max retries exceeded with url: /api/common/1.0/services (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f862ad8c610>: Failed to establish a new connection: [Errno 111] Connection refused',))`

Is there a port on either my Client machine or the NetProfiler machine that needs to be opened?

**Comment by mgarabed** [comment]
Unless you've changed the default port, you should only need to access 443 on the NetProfiler.

Is there a firewall rule in the way?

**Comment by ericgcoker** [comment]
Yes. I was not able to telnet via 443 between the client machine and the one with Riverbed. Thanks
